/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class robot_tangwa_discreminationphone_JniTest */

#ifndef _Included_robot_tangwa_discreminationphone_JniTest
#define _Included_robot_tangwa_discreminationphone_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     robot_tangwa_discreminationphone_JniTest
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_robot_tangwa_discreminationphone_JniTest_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
